- CONTRIBUTING.md
> docs: 컨트리뷰션 가이드 추가

- .gitignore
- backend/package-lock.json
- backend/package.json
- backend/router/main.js
- backend/server.js
- resolved #19  
NeDB를 설치하고 express에서 회원가입 post 요청을 받았을 때 db에 회원 정보를 저장하는 코드 작성
db에 저장을 성공하면 { success : 1 } JSON 응답.
> feat: 데이터베이스 구현  #19

- frontend/public/css/style.css
#17 
체크박스 선택시에 label::after의 이미지를 바꾸는 방법으로 체크박스 기능을 구현했습니다.
> feat: 체크박스 선택시 이미지 바꾸기

- public/css/style.css
- resolved #27 
firefox와 safari에서도 동일한 뷰를 지원하도록 수정하였습니다.
> fix: safari와 firefox에서도 동일한 뷰를 지원하도록 수정 #27

- public/js/index.js
- views/sign-up.html
- resolved #17
- 회원가입 페이지에 전체 약관 동의 버튼 클릭시 필수, 선택 모두 체크
- 필수, 선택이 모두 체크 상태일 경우에만 전체 동의 버튼 체크
> feat: 회원가입 페이지 약관 체크 기능 구현 #17

- router/main.js
- router/router.js
- router/utils.js
- server.js
- views/sign-up-complete.pug
- views/sign-up.html
- views/sign-up.pug
- resolved #28 
html 문서로 먼저 작성했는데 이를 pug로 변환했습니다.
> feat: html 마크업 pug 템플릿으로 변환

- router/router.js
- router/utils.js
- resolved #16 
프론트엔드에서 로그인 폼 정보를 POST 리퀘스트로 보내주면 이 정보를 바탕으로  
아이디 중복체크를 하고 존재 하지 않는 아이디면 회원정보를 데이터베이스에 저장하는 기능 구현
이 때 패스워드는 암호화하여 저장합니다.
> feat: 회원가입 기능 구현 #16

- public/css/style.css
- public/js/index.js
- views/sign-up.html
- views/sign-up.pug
- resolved #14 
다음 주소 api 사용하는 기능 추가했습니다. ui는 배민 상회 앱과 완전히 일치하게 하진 못했습니다.
> feat: 회원가입 페이지 선택 정보 주소 기능 구현 #14

- public/css/style.css
- public/js/validation.js
- router/utils.js
- views/sign-up.pug
- resolved #12 
입력 양식에 맞지 않아 에러 메세지가 나올경우 강조하는 CSS 적용
> feature: 회원가입 페이지 입력 조건 기능 구현 #12

- public/css/style.css
- public/js/validation.js
- views/sign-up.pug
- resolved #18 
가입완료 버튼을 선택했을 때, 현재 오류가 있는 영역이 있다면 해당 input 창으로 포커스 이동
오류 있는 영역이 여러 개 있을 경우에는 위에 있는 input 창으로 포커스 이동
가입완료 버튼을 눌렀을 때 성공 시, 백엔드에 post request 보내기
아이디만 입력한 상태에서 가입 완료 버튼을 누른 후 결과 화면
> feat: 회원가입 페이지 가입 완료 버튼 기능 구현 #18

- public/css/style.css
- router/router.js
- views/login.pug
- views/main.pug
- resolved #7 
메인페이지 제작
로그인 버튼을 누르면 로그인 페이지로  
회원가입을 누르면 회원가입 페이지로 이동
> feat: 메인 페이지 마크업 #7

- router/router.js
- router/utils.js
- views/login.pug
- resolved #15 
안전한 패스워드 기법으로 로그인 기능을 구현했습니다.
> feat: 로그인 기능 구현 resolve #15

- public/js/terms.js
terms.js updateCheckBox 함수 간략하게 리팩토링했습니다.
> refactor: updateCheckBox 함수 리팩토링

- package-lock.json
- router/router.js
- router/utils.js
- server.js
> feat: 로그인 성공 시 세션 사용 기능 추가 #15

- public/js/phone-auth.js
- router/utils.js
- views/sign-up-complete.pug
- views/sign-up.pug
> feat: 회원가입 성공시 회원가입 페이지로 이동 #18

- router/utils.js
- views/login.pug
> feat: 로그인 실패 시 에러메시지 노출 #11

- public/css/style.css
- public/js/email.js
> refactor: email 관련 함수 리팩토링

- public/js/validation.js
- router/router.js
- router/utils.js
- resolved #12 
회원가입할때 아이디 중복체크 비동기로 확인하는 코드 추가
> feat: 회원가입 폼 입력할때 아이디 중복 체크 #12

- public/js/find-address.js
- public/js/option-info.js
> fix: 주소 및 상세 주소 입력 부분 클릭 시 우편번호 찾기 팝업 창 뜨는 에러 수정

- public/js/phone-auth.js
- resolved #45 
- 휴대폰 인증 부분에서 핸드폰 번호 10자리 이하일 경우 인증번호 전송 안함.
- 재전송시 타이머 중복되는 오류 수정
> fix: 휴대폰 인증 부분 오류 수정 #45

- views/login.pug
> fix: 로그인 페이지 회원가입 링크 추가

- public/js/phone-auth.js
> fix: 타이머가 즉시 실행되어 콘솔 창에 에러가 표시되는 문제 해결

- public/js/validation.js
async, await 사용하여 프로미스 반환되는 문제 해결
- resolved #12 
에러메세지에 프로미스가 리턴돼서 항상 에러로 인식하던 문제 해결
> fix: 아이디 중복체크 프로미스 문제 해결

- public/js/phone-auth.js
> feat: 핸드폰 인증 완료 시 버튼 이름 변경 #13

- public/js/phone-auth.js
> fix: 타이머가 중복 실행되는 문제 해결 #51
